import os, json
from openai import AzureOpenAI

client = AzureOpenAI(
    api_version="2024-12-01-preview",
    azure_endpoint="https://nmsr-mdkdg6wh-eastus2.cognitiveservices.azure.com/",
    api_key="Fh5w6tZj2Qgha4TZGSKAa5tq9QqKP7oummUj0iYByi5sSuRoV3n0JQQJ99BGACHYHv6XJ3w3AAAAACOGlvT5"
)

x = """
# ROLE 
YOU CAN USE ANY LANGUAGE NOT ONLY ENGLISH

You are an advanced flashcard creator specializing in graduate and post-graduate level content. high-quality flashcards on the given topic. Follow these guidelines:

# INSTRUCTIONS:
  1. Check the context language and create flashcards in that language.
  2. Questions should be challenging and in-depth, suitable for graduate or post-graduate level study.
  3. Avoid basic definitions or questions that can be answered with a single word from the topic itself.
  4. Answers MUST BE CONCISE, but may contain multiple words or a short phrase when necessary for accuracy. Answers MUST NOT BE MORE THAN 5 WORDS LONG.
  5. Ensure all answers are unique with no repetitions.
  6. Cover a diverse range of subtopics within the main topic to provide comprehensive coverage.
  7. Include questions that test understanding of concepts, theories, applications, and critical thinking.
  8. Avoid questions that can be answered with a simple "yes" or "no".
  9. Complete All the flashcards in the JSON format provided below.
  
# IMPORTANT
    - **Language** in Flashcard Question and Answer Depends On Context Language in FRONT AND BACK OF THE FLASHCARD THE WHOLE FLASHCARD DEPENDS ON CONTEXT LANGUAGE
    - For MATH Equations Use **LaTeX** for **Math Equation** Or **Any Equation** Use **LaTeX** Instead Of Normal English Letters and Number

# CONTEXT:
[Context]

# JSON FORMAT:

  Return the flashcards in the following JSON format:

  {
    "flashcards": [
      {
        "front": "Detailed, challenging question related to the topic",
        "back": "Concise, accurate answer (can be a short phrase if needed)"
      }
    ]
  }

Example topic: "Fundamentals of Psychology"
Instead of "Which branch studies the human mind?", ask something like:
"What cognitive bias describes the tendency to search for or interpret information in a way that confirms one's preexisting beliefs?"
Answer: "Confirmation bias"
"""

completion = client.chat.completions.create(
  model="examtieai", # Replace with your model dpeloyment name.
  messages=[
    {"role": "system", "content": x},
    {"role": "user", "content": "สร้างแฟรการ์ด เกี่ยวกับ ตีโกณมิติ มัธยมศึกษาปีที่ 5 จำนวน 5 แฟรชการ์ด."}
  ]
)

# `print(completion.choices[0].message)` is printing the response generated by the chat completion
# model for the user message "When was Microsoft founded?" The response is stored in the `message`
# attribute of the first choice in the `choices` list within the completion object.
message = completion.choices[0].message.content
print(message)
#print(completion.model_dump_json(indent=2)
if message.startswith("```json"):
    message = message.split("```json")[-1]
    message = message.rsplit("```", 1)[0].strip()

try:
    flashcards = json.loads(message)
    print(flashcards)
except json.decoder.JSONDecodeError as e:
    print("Error loading JSON:", e)
"""
ChatCompletionMessage(content='{\n  "flashcards": [\n    {\n      "front": "จงพิสูจน์ว่า $\\\\tan(\\\\alpha+\\\\beta)=\\\\frac{\\\\tan\\\\alpha+\\\\tan\\\\beta}{1-\\\\tan\\\\alpha\\\\tan\\\\beta}$ โดยแสดงขั้นตอนตั้งแต่สูตร $\\\\sin$ และ $\\\\cos$",\n      "back": "นิยาม tan จาก sin cos"\n    },\n    {\n      "front": "หาค่าของ $\\\\sin15^\\\\circ$ โดยใช้สูตรผลต่างมุม",\n      "back": "$\\\\frac{\\\\sqrt6-\\\\sqrt2}{4}$"\n    },\n    {\n      "front": "จงพิสูจน์อัตลักษณ์ $\\\\sin^2\\\\theta-\\\\cos^2\\\\theta=-\\\\cos2\\\\theta$",\n      "back": "สูตร cos2θ=1-2sin²θ"\n    },\n    {\n      "front": "แก้สมการ $\\\\sin x=\\\\tfrac{\\\\sqrt3}{2}$ ในช่วง $0\\\\le x<2\\\\pi$",\n      "back": "$\\\\tfrac{\\\\pi}{3},\\\\tfrac{2\\\\pi}{3}$"\n    },\n    {\n      "front": "แสดงวิธีแปลง $\\\\sin A+\\\\sin B$ ให้เป็นผลคูณ",\n      "back": "$2\\\\sin\\\\tfrac{A+B}{2}\\\\cos\\\\tfrac{A-B}{2}$"\n    }\n  ]\n}', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None)
"""